# ASTR 310 HW6

## 1. Working with NumPy  
Name:Maxwell Fazen 

Net ID: mfazen2    

**Working with NumPy
Write Python code fragments using NumPy data structures, types, and operations to perform
the following operations.**   
*Avoid explicit iterations over arrays!*


**a)** (a) The function `numpy.random.random_sample()` allows you to create an array with random values in the range \[0.0, 1.0\). You can multiply the output by a scaling factor and add an offset to it to get it to lie in a different range. Create a 10 x 10 array initialized with random numbers that lie between 3 and 10, then compute the average of the array. (4 points)


In [6]:
# Code here
import numpy as np
A = ((10-3)*np.random.random_sample((10,10))+3)
av = np.average(A)
print(av)

6.7050349963339375


**b)** reate a 1D array containing angles in degrees: 0, 15, 30, ... 90 (i.e., every 15 degrees up to
90). Now create 3 new arrays with the sine, cosine, and tangent of the elements of the first
array. Finally, calculate the inverse sine, inverse cosine, and inverse tangent of the arrays
above and compare to the original angles. Compute the fractional error where possible. (5 points)

In [19]:
# Code here
B = np.linspace(0,90,7)
print(B)
sinB = np.sin(B*np.pi/180)
cosB = np.cos(B*np.pi/180)
tanB = np.tan(B*np.pi/180)

asinB = np.arcsin(sinB)*180/np.pi
acosB = np.arccos(cosB)*180/np.pi
atanB = np.arctan(tanB)*180/np.pi
print(asinB)
print(acosB)
print(atanB)
##no fractional error?

[ 0. 15. 30. 45. 60. 75. 90.]
[ 0. 15. 30. 45. 60. 75. 90.]
[ 0. 15. 30. 45. 60. 75. 90.]
[ 0. 15. 30. 45. 60. 75. 90.]


**c)** NumPy has a standard deviation function, numpy.std(), but here we'll write our own
that works on a 1D array. The standard deviation is a measure of the “width” of the
distribution of numbers in the array. Given an array $a$ and its average ${\bar a}$, the standard
deviation is given by

$$\sigma = \left[{1\over N}\sum_{i=0}^{N-1} (a_i - {\bar a})^2\right]^{1/2}\ .$$

Card-carrying statistics aficionados will remind you that if you have to compute $\bar{a}$ from the
data themselves you should normalize by $1/(N-1)$ rather than $1/N$, but we won't worry
about that for now.  Write a function to calculate the standard deviation for an input array $a$. Test your
function on a random array with 100 elements, and compare to the built-in
numpy.std(). (5 points)

In [22]:
# Code here
def stdev(a):
    mean = np.mean(a)
    total = np.sum((a-mean)**2)
    out = (total/a.size)**(1/2)
    return out
test = np.random.randint(100,size=100)
print(stdev(test))
print(np.std(test))


28.655001308672105
28.655001308672105


**d)** Given a scalar value $x$ and a NumPy array $v$, write code to find the value in $v$ that is
closest to $x$. Do not assume $v$ is sorted. Test your code with an array containing 100
random numbers between 5 and 50 and $x$ = 25 (4 points)

In [53]:
# Code here
x = 25
v = np.random.randint(5,50,size=100)
print(v)
def find(target,arr):
    index = (np.abs(arr-target)).argmin()
    return index
print(v[find(x,v)])

[49 43 45 21 22 17 20 39 17 13 13 26 48  7 16 12 41 45 32 43 42 15 23  5
 37 37 14 18 22 46 40 25 26 48 21 24 11 27 47 47 13 28 46 22 24 37 19 18
 42 37 20 45 10 46 33  9 10 31  8 32 13  5 16 33 17 21 44 33 48 30 48 38
 20 16 32  6 12 46 33 27 25 29 44 49 39 49 35 30 29  7 32 15 21 37 10 41
 40 14 31 40]
25


**e)** Create a one-dimensional array $x$ containing 100 randomly selected values between 0
and $2\pi$. Sort the array. Create another 1D array $y$ in which the $j$th element contains

$$y_j = \sin^2 x_j \cos x_j\ .$$

Next use the trapezoidal rule to integrate $y$ on this interval. Recall that the trapezoidal rule is given by

$$\int_a^b y(x)\,dx \approx \sum_{j=0}^{N-2} {1\over 2}(y_j + y_{j+1})(x_{j+1}-x_j)\ .$$

Finally, produce two arrays containing, respectively, those $x$- and $y$-points from the grid for which $y > 0.25$. (7 points)

In [81]:
# Code here
X = np.sort(2*np.pi*np.random.random_sample(100))
Y = ((np.sin(X))**2)*np.cos(X)
integ = np.sum(0.5*((X[1:]-X[:-1])*(Y[1:]+Y[:-1])))
print(integ)
YY = (Y) > .25
XX = X[YY]
YY = Y[YY]
print(YY)
print(XX)

-0.00882762861331439
[0.29505619 0.36769767 0.38012982 0.38481694 0.38186027 0.37920678
 0.36176154 0.27061793 0.30218539 0.30292544 0.34648791 0.3844441
 0.37994655 0.37961953 0.37958608 0.37780826 0.37257588 0.25871773]
[0.65643848 0.83073802 0.89044765 0.96379879 1.00636683 1.02508439
 1.09555678 1.26950892 5.06174025 5.06295723 5.14718708 5.30803826
 5.39398574 5.39615814 5.3963766  5.40715837 5.43289546 5.69064793]


## 2. Rise and set times of Betelgeuse with Astropy

Using Astropy we can get the altitude and azimuth of an object at a given location and time,
eg. using    

```
from astropy.coordinates import EarthLocation, SkyCoord, AltAz
from astropy.time import Time
obsloc = EarthLocation.of_address("1002 W. Green St., Urbana, IL")
target = SkyCoord.from_name("Betelgeuse")
obstime = Time(Time.now(), location=obsloc)
altaz = target.transform_to(AltAz(obstime=obstime, location=obsloc))
```
  
Here obstime by default uses the UTC time scale, and the altaz object has altitude (alt)
and azimuth (az) attributes that are Angle objects. Notice that here the observation time is
taken to be “now,” i.e. whenever the code is run. The Time constructor can also accept different
time specifications; use help(Time) or the Astropy documentation to find out how to create a
Time object for a given date and time.  


With this information, write a function to use binary search to find the times on a given date
when Betelgeuse has an altitude of zero to within one second, and determine which is the rise
time and which is the set time. We suggest that you specify the date using a (month, day, year)
tuple. Hints:

**a)** Take your initial search intervals to be (obstime-12*u.hour, obstime) and (obstime,
obstime+12*u.hour), where obstime is taken to be noon CST on the specified date. (7 points)

In [95]:
# Code here
from astropy.coordinates import EarthLocation, SkyCoord, AltAz
from astropy.time import Time
from astropy import units as u
date = (3,4,2024)
target = SkyCoord.from_name("Betelgeuse")
obsloc = EarthLocation.of_address("1002 W. Green St., Urbana, IL, USA")
def find_riseset(date,obsloc,target):
    month,day,year = date[0],date[1],date[2]
    noon_cst = Time(str(year)+'-'+str(month).zfill(2)+\
        '-'+str(day).zfill(2)+' 12:00:00',scale='utc') + 6*u.hour
    low_time = noon_cst
    high_time = noon_cst + 12*u.hour
    while (high_time - low_time).sec > 1.0:
        mid_time = low_time + (high_time - low_time) / 2
        alt_low = target.transform_to(AltAz\
                        (obstime=low_time, location=obsloc)).alt
        alt_mid = target.transform_to(AltAz\
                        (obstime=mid_time, location = obsloc)).alt
        if alt_low < 0 and alt_mid >= 0:
            high_time = mid_time
        else:
            low_time = mid_time
    rise_time1 = low_time - 6*u.hour
    set_time1 = high_time - 6*u.hour
    low_time = noon_cst - 12*u.hour
    high_time = noon_cst
    ##do two binary searches to cover the entire day
    while (high_time - low_time).sec > 1.0:
        mid_time = low_time + (high_time - low_time) / 2
        alt_low = target.transform_to(AltAz\
                        (obstime=low_time, location=obsloc)).alt
        alt_mid = target.transform_to(AltAz\
                        (obstime=mid_time, location = obsloc)).alt
        if alt_low < 0 and alt_mid >= 0:
            high_time = mid_time
        else:
            low_time = mid_time
    rise_time2 = low_time - 6*u.hour
    set_time2 = high_time - 6*u.hour
    print(f'Betelgeuse rise time at \
          {np.minimum(rise_time2,rise_time1)} CST')
    print(f'Betelgeuse set time at \
          {np.maximum(set_time2,set_time1)} CST')
find_riseset(date,obsloc,target)

Betelgeuse rise time at           2024-03-04 11:59:59.341 CST
Betelgeuse set time at           2024-03-04 12:32:10.737 CST


**b)** If you difference two Time objects you get a TimeDelta object that can be directly compared
to a
float representing a number of seconds, or added to another Time object. So in
implementing a binary search you can iterate until the difference between your upper search
limit and your lower search limit is less than one second. You can also add one-half the
difference to the lower search limit to get the time corresponding to the middle of the range. <br> (10 points)

In [ ]:
#Code Here


**c)** To determine whether the next iteration of the binary search should search in the range
(low, middle) or (middle, high), use the altitude of Betelgeuse at each of the three times.
For example, if the altitude is negative for the lower time and positive for the middle time,
then the time when the altitude is zero must lie in the (low, middle) interval, and you would
set the higher time equal to the middle time for the next iteration.<br>
*Evaluate your function for March 4, 2024 and print the rise and set times in a user-friendly
format. Express times in our local time zone (ie. CST).* (8 points)

In [ ]:
#Code Here

The cell below only works for Google Colab. It does not support other Jupyter notebook environments, such as VSCode or Anaconda. If you choose to use those enviroments, feel free to remove the cell below.

In [ ]:
%%capture
# Here we use a script to generate pdf and save it to google drive.

# After executing this cell, you will be asked to link to your GoogleDrive account.
# Then, the pdf will be generated and saved to your GoogleDrive account and you need to go there to download;

from google.colab import drive
drive.mount('/content/drive')
# install tex; first run may take several minutes
! apt-get install texlive-xetex
# file path and save location below are default; please change if they do not match yours
! jupyter nbconvert --output-dir='/content/drive/MyDrive/' '/content/drive/MyDrive/Colab Notebooks/HW6_ASTR310.ipynb' --to pdf