Exercise 1:
mfazen2

In [33]:
import numpy as np
A = np.logspace(-3,7,200).reshape(10,5,4)
print(A[3,0,2],A[5,4,1])
print(A[9,4,3])

B = np.array([-2,8,10,1,17,9,2,0,1,6,-4,10,3,8,-9,4]).reshape(4,4)
B[(B>4)] = 4
print(B)


C = np.zeros((10,10))
C[::2,::2]  = 1
print(C)





1.3049019780144029 757.525025877192
10000000.0
[[-2  4  4  1]
 [ 4  4  2  0]
 [ 1  4 -4  4]
 [ 3  4 -9  4]]
[[1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Exercise 2:

In [71]:
x = np.linspace(-np.pi,np.pi,10)
y = np.linspace(-np.pi,np.pi,10)

x, y= np.meshgrid(x,y)
def func(x, y):
    return np.sin(x)*np.cos(y)
z = func(x, y)

s = z[3:7,3:7].sum()
print("sum:",s)

def f(x):
    return np.square(x)
squared = f(z)
print(squared)
print(f(2))

maxyval = np.max(z,0)
print(maxyval)

sum: -6.661338147750939e-16
[[1.49975978e-32 4.13175911e-01 9.69846310e-01 7.50000000e-01
  1.16977778e-01 1.16977778e-01 7.50000000e-01 9.69846310e-01
  4.13175911e-01 1.49975978e-32]
 [8.80095168e-33 2.42461578e-01 5.69129177e-01 4.40118067e-01
  6.86453782e-02 6.86453782e-02 4.40118067e-01 5.69129177e-01
  2.42461578e-01 8.80095168e-33]
 [4.52232910e-34 1.24587782e-02 2.92444446e-02 2.26152672e-02
  3.52731162e-03 3.52731162e-03 2.26152672e-02 2.92444446e-02
  1.24587782e-02 4.52232910e-34]
 [3.74939946e-33 1.03293978e-01 2.42461578e-01 1.87500000e-01
  2.92444446e-02 2.92444446e-02 1.87500000e-01 2.42461578e-01
  1.03293978e-01 3.74939946e-33]
 [1.32432122e-32 3.64843511e-01 8.56395844e-01 6.62266666e-01
  1.03293978e-01 1.03293978e-01 6.62266666e-01 8.56395844e-01
  3.64843511e-01 1.32432122e-32]
 [1.32432122e-32 3.64843511e-01 8.56395844e-01 6.62266666e-01
  1.03293978e-01 1.03293978e-01 6.62266666e-01 8.56395844e-01
  3.64843511e-01 1.32432122e-32]
 [3.74939946e-33 1.03293978e-0

Exercise 3

In [92]:
import numpy.random as npr
x = y = npr.rand(100)
xx, yy = np.meshgrid(x,y)
print(x, y)
z = np.exp(-(xx**2+yy**2)/0.05)
print(z)


[0.60790076 0.22481928 0.81454029 0.94777685 0.80610805 0.7835694
 0.23752414 0.81029785 0.40734432 0.99428266 0.93894433 0.34683882
 0.58361218 0.53237169 0.57944507 0.97941279 0.6477708  0.05211813
 0.56420262 0.3892125  0.49254148 0.18781467 0.37805646 0.96193086
 0.41578352 0.8119388  0.07483509 0.1386452  0.24235476 0.09644438
 0.2825253  0.55711198 0.09973466 0.86207423 0.69654623 0.42799095
 0.35325021 0.54352766 0.13924223 0.81765811 0.61432396 0.7235495
 0.97760034 0.68643882 0.66479579 0.41086392 0.27069048 0.6199522
 0.52849955 0.90227391 0.25265453 0.63625894 0.93720843 0.28242908
 0.03459399 0.38839518 0.32641415 0.11176022 0.04628303 0.90779929
 0.63420448 0.90424314 0.05262352 0.48968603 0.54829012 0.98670871
 0.22248161 0.39547686 0.26474316 0.40020778 0.84140298 0.8312649
 0.82104502 0.81863269 0.22167239 0.2623814  0.96120916 0.60172734
 0.65004243 0.16886399 0.37096176 0.26549246 0.12695331 0.95838651
 0.79886648 0.09409427 0.95546293 0.00957222 0.47225322 0.25875853

In [108]:
hist,bin_edges =np.histogram(z,bins=10)
numcount = 1
edgecount = 0.0
print(bin_edges)
for val in hist:
    print(f"{numcount:2}). {edgecount:2.1f} {edgecount+.1:2.1f}{val:7}")
    numcount+=1
    edgecount+=.1

[6.70337736e-18 9.96341614e-02 1.99268323e-01 2.98902484e-01
 3.98536646e-01 4.98170807e-01 5.97804968e-01 6.97439130e-01
 7.97073291e-01 8.96707453e-01 9.96341614e-01]
 1). 0.0 0.1   9274
 2). 0.1 0.2    225
 3). 0.2 0.3    195
 4). 0.3 0.4     97
 5). 0.4 0.5     36
 6). 0.5 0.6     33
 7). 0.6 0.7     53
 8). 0.7 0.8     37
 9). 0.8 0.9     28
10). 0.9 1.0     22
